#!/usr/bin/env bash

app="$(basename "$0")"
phpversion="$1"
action="$2"

opcache_conf_path="$(brew --prefix)/etc/php/$phpversion/conf.d"
opcache_conf_file="ext-opcache.ini"
opcache_conf=$opcache_conf_path/$opcache_conf_file

if [ "$phpversion" == "" ]; then
    echo ""
    echo "You need specify php version, e.g: 7.0"
    echo "Usage: ${app} <php_version> <on | off>"
    echo ""

    exit 1

else     
    if [ ! -f "$opcache_conf" ] && [ ! -f "$opcache_conf.disabled" ]; then
        echo ""
        echo "The ini file for opcache was not found at '$opcache_conf_path'"
        echo "Did you install opcache via Homebrew?"
        echo ""

        exit 1
    else
        STATUS="enabled"

        if [ -f "$opcache_conf" ] && [ -f "$opcache_conf.disabled" ]; then
            echo ""
            echo "Detected both enabled and disabled opcache ini files. Deleting the disabled one."
            echo ""

            rm -rf "$opcache_conf.disabled"
            STATUS="enabled"
        elif [ -f "$opcache_conf.disabled" ]; then
            STATUS="disabled"
        fi

        if [ $# -ge 1 ] && [ "$action" == "on" ] || [ "$action" == "s" ] || [ "$action" == "off" ] || [ "$action" == "o" ]; then
            if [ "$action" == "on" ] || [ "$action" == "s" ]; then
                mv "$opcache_conf.disabled" "$opcache_conf" 2> /dev/null
                STATUS="enabled"
            elif [ "$action" == "off" ] || [ "$action" == "o" ]; then
                mv "$opcache_conf" "$opcache_conf.disabled" 2> /dev/null
                STATUS="disabled"
            fi
            echo ""
            echo "opcache has been $STATUS, restarting PHP"

            launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.php@"${phpversion}".plist
            launchctl load ~/Library/LaunchAgents/homebrew.mxcl.php@"${phpversion}".plist
        else
            echo ""
            echo "Usage: ${app} <php_version> <on | off>"
        fi

        echo ""
        echo "You are running PHP v$phpversion with opcache $STATUS"
        echo ""
    fi
fi

